[build]
command = "yarn build"
publish = "build/"


[build.processing]
css = { bundle = true, minify = true }
js = { bundle = true, minify = true }
html = { pretty_urls = true }
images = { compress = true }

[template.environment]
SYSTEM_ID = "Your System ID"
PK_TOKEN_AUTH = "use pk;token to get your API Token"
REACT_APP_CUSTOM_MESSAGE = "A short message you want to display under your system's status"

